"""add_page_number_to_file_chunks

Revision ID: 41c4e4b0ad87
Revises: b880e7502535
Create Date: 2026-04-20 18:57:38.241215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '41c4e4b0ad87'
down_revision: Union[str, None] = 'b880e7502535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_chunks', sa.Column('page_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_chunks', 'page_number')
    # ### end Alembic commands ###
