"""add_files_and_file_chunks

Revision ID: 5bd1a348bc84
Revises: 7a5f0652bfe8
Create Date: 2026-04-20 15:26:40.850659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '5bd1a348bc84'
down_revision: Union[str, None] = '7a5f0652bfe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('minio_path', sa.String(), nullable=False),
    sa.Column('index_status', sa.Enum('pending', 'indexing', 'indexed', 'failed', 'unsupported', name='indexstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_user_id'), 'files', ['user_id'], unique=False)
    op.create_table('file_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_chunks_file_id'), 'file_chunks', ['file_id'], unique=False)
    op.create_index(op.f('ix_file_chunks_user_id'), 'file_chunks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_chunks_user_id'), table_name='file_chunks')
    op.drop_index(op.f('ix_file_chunks_file_id'), table_name='file_chunks')
    op.drop_table('file_chunks')
    op.drop_index(op.f('ix_files_user_id'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
